use_frameworks!

xcodeproj 'CRUConfig', 'CRUConfig-Example' => :release, 'CRUConfig-Example-Beta' => :release, 'CRUConfig-Example-Release' => :release

pod 'CRUConfig', :path => '../'

target 'CRUConfig_Tests', :exclusive => true do
  pod 'CRUConfig', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
