platform :ios, '8.0'
use_frameworks!

abstract_target 'CRUConfig' do

	pod 'CRUConfig', :path => '../'
	
	target 'CRUConfig_Example' do
		project 'CRUConfig', 'CRUConfig-Example' => :release, 'CRUConfig-Example-Beta' => :release, 'CRUConfig-Example-Release' => :release
	end

	target 'CRUConfig_Tests' do
	  pod 'Specta'
	  pod 'Expecta'
	end
end
