use_frameworks!

target 'CRUConfig_Example', :exclusive => true do
  pod 'CRUConfig', :path => '../'
end

target 'CRUConfig_Tests', :exclusive => true do
  pod 'CRUConfig', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
